Added basic testing and made changes in seq driver: - A line started with // (instead of //[:space:]) is a comment. - Driver and PRIMME configuration can be in the same file. - Driver parameters and the method are also printed at beginning of the execution. - Added the next parameters to driver configuration:   - initialGuessesFileName, to load initial vectors from a file;   - initialGuessesPert, to perturbed them;   - saveXFileName, to store the computed eigenvectors; and   - checkXFileName, to compare the computed eigenvectors with previous solution (used for testing).

diff --git a/DTEST/Makefile_seq b/DTEST/Makefile_seq
--- a/DTEST/Makefile_seq
+++ b/DTEST/Makefile_seq
@@ -58,3 +58,21 @@ ddependencies_seq:
 all: seq_dprimme
 seq_dprimme: $(DRIVEROBJECTS)
 include ddependencies_seq
+
+all_tests: seq_dprimme
+	@ok="0";echo "Please wait, this could take a while...";\
+	for i in tests/test_??? ; do \
+		echo "********** Test $$i ***********"; \
+		./seq_dprimme $$i || ok="1"; \
+	done > tests.log 2>&1;\
+	if test $$ok -eq 0 ; then \
+		echo "All tests passed!"; \
+	else\
+		cat tests.log;\
+		echo "Some tests fail. Please consider to send us the file";\
+		echo "DTEST/tests.log if the software doesn't work as expected.";\
+		exit 1;\
+	fi
+
+test: seq_dprimme
+	./seq_dprimme tests/test_003
